### ISSUE TITLE
Delete button position

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab-contrib/jlab-enhanced-cell-toolbar#11]
In VS Code, the delete button is on the far right of the toolbar - after discussions with user this may come as a way to mitigate clicking by error on it. Should we do the same?

**Comment by ParasKoundal** [comment]
YES. YES. YES. I was looking for a solution for this only when I came across this post.

**Comment by fcollonval** [comment]
@ParasKoundal in the latest released version (2.1 and 3.1), you can now define custom left and right menus; see [README](https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar#settings).

**Comment by ParasKoundal** [comment]
Thanks a lot. Works Perfectly.
