### ISSUE TITLE
Suggestion: Add option to disable everything but displaying the tags

### ISSUE THREAD

**Issue by Phoemuex** [jupyterlab-contrib/jlab-enhanced-cell-toolbar#17]
I really like the way the extension displays the tags for every cell.

For my application, however, I would like to disable all the remaining features - in particular the buttons for moving cells up/down.

Would it be possible to add an option in the settings to achieve this?

**Comment by fcollonval** [comment]
Thanks for reaching out @Phoemuex 

Yes it should be easy to achieve by filtering the `POSITIONED_BUTTONS` list with the one specified by a setting or to skip that statement with a boolean setting:

https://github.com/jupyterlab-contrib/jlab-enhanced-cell-toolbar/blob/0853ad57c579cff25442cc2189688dbb77acb76b/src/celltoolbartracker.ts#L147

PRs are welcomed if you want to give it a try.
